### ISSUE TITLE
where to download vmmap64.exe ?

### ISSUE THREAD

**Issue by lonnywong** [Byzero512/wibe#1]
```
Thread 1 hit Breakpoint 1, 0x0000000000401782 in main ()
'vmmap64.exe' is not recognized as an internal or external command,
operable program or batch file.
Python Exception <class 'subprocess.CalledProcessError'> Command 'vmmap64.exe -pid 36208 -all' returned non-zero exit status 1.:
```

1. download from [microsoft](https://docs.microsoft.com/en-us/sysinternals/downloads/vmmap), not working.
2. download from [vmmap-win-cmd](https://github.com/Byzero512/vmmap-win-cmd), no vmmap64.exe, just vmmap.exe in Release, and not working.

**Comment by Byzero512** [comment]
change name of vmmap(X64) to vmmap64
